### ISSUE TITLE
Broken on Tor Browser maximum security mode

### ISSUE THREAD

**Issue by theel0ja** [AnXh3L0/anxh3l0.github.io#2]
![screen shot 2018-10-27 at 18 29 41](https://user-images.githubusercontent.com/5832930/47605986-4a91b980-da16-11e8-8d46-e70c0708fc73.png)

<img width="1112" alt="screen shot 2018-10-27 at 13 25 05" src="https://user-images.githubusercontent.com/5832930/47605985-3fd72480-da16-11e8-9f59-80a0daa1b14b.png">

**Comment by AnXh3L0** [comment]
Fixed by 4bcef5b

**Comment by AnXh3L0** [comment]
Closing
